# Generated by scripts/render-formula.sh in smhasan94/rotate from
# packaging/homebrew/rotate.rb.tmpl. The release workflow overwrites this
# file on every release; change the template there instead.
class Rotate < Formula
  desc "Revoke and rotate leaked secrets safely, end to end"
  homepage "https://github.com/smhasan94/rotate"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/smhasan94/rotate/releases/download/v1.2.3/rotate-1.2.3-aarch64-apple-darwin.tar.gz"
      sha256 "06002459dda36f9e79a938bad5b0ad877ee0ab98bb68ae1ada7ab565e11d349a"
    end
    on_intel do
      url "https://github.com/smhasan94/rotate/releases/download/v1.2.3/rotate-1.2.3-x86_64-apple-darwin.tar.gz"
      sha256 "aa9be5db014340fc43c84c96db9d1642d54389430ba2eb31257bf6587388df95"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/smhasan94/rotate/releases/download/v1.2.3/rotate-1.2.3-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "fc055342b8238aff04afdcbf7002ca0f487221ed42627353c72811d36574163f"
    end
    on_intel do
      url "https://github.com/smhasan94/rotate/releases/download/v1.2.3/rotate-1.2.3-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "7d83fd93052da40add312bf7ddbf84f12d140d39802a33fe472003d385cac3cc"
    end
  end

  def install
    bin.install "rotate"
  end

  test do
    assert_equal "rotate #{version}", shell_output("#{bin}/rotate --version").strip
  end
end
